---
title: "Alports Quantifying Number of DEGs by Cell Type: 6M_Alp vs. WT"
author: "Jonathan Nelson and Annie Lackey"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document: 
    toc: yes
    toc_depth: 3
    toc_float: true
    number_sections: yes
    theme: bootstrap
    df_print: paged
    code_folding: hide
    highlight: pygments
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r load new packages, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}

if (!require("dplyr")) {install.packages("dplyr"); require("dplyr")}
if (!require("Seurat")) {install.packages("Seurat"); require("Seurat")}
if (!require("patchwork")) {install.packages("patchwork"); require("patchwork")}
if (!require("knitr")) {install.packages("knitr"); require("knitr")}
if (!require("ggplot2")) {install.packages("ggplot2"); require("ggplot2")}
if (!require("BiocManager")) {install.packages("BiocManager"); require("BiocManager")}
if (!require("tibble")) {install.packages("tibble"); require("tibble")}
if (!require("ggpmisc")) {install.packages("ggpmisc"); require("ggpmisc")}
if (!require("RColorBrewer")) {install.packages("RColorBrewer"); require("RColorBrewer")} #color
if (!require("ggrepel")) {install.packages("ggrepel"); require("ggrepel")}
if (!require("DESeq2")) {BiocManager::install('DESeq2'); require("DESeq2")}
if (!require("here")) {install.packages("here"); require("here")}
if (!require("stringr")) {install.packages("stringr"); require("stringr")}
if (!require("car")) {install.packages("car"); require("car")}
if (!require("openxlsx")) {install.packages("openxlsx"); require("openxlsx")}
if (!require("readxl")) {install.packages("readxl"); require("readxl")}
if (!require("data.table")) {install.packages("data.table"); require("data.table")}
if (!require("ggvenn")) {install.packages("ggvenn"); require("ggvenn")}
if (!require("kableExtra")) {install.packages("kableExtra"); require("kableExtra")} # for color brewer

```


# Load Alports Dataset

```{r load data, echo=TRUE, warning=FALSE, error=FALSE, message=FALSE}

SO <- readRDS(here("outputs", "Alports_041525.rds"))

DimPlot(SO)

SO

```

# Condition DEGs for Alports Dataset

```{r echo=TRUE, warning=FALSE, error=FALSE, message=FALSE, results = "asis"}

SO2 <- subset(SO, subset = group == "6M_Alp")

clusters <- unique(SO2@meta.data$class_merge)
names(clusters) <- clusters

SO <- PrepSCTFindMarkers(SO)
DEG.env <- new.env()

Idents(SO) <- SO@meta.data$class_merge

rm(SO2)

for (i in clusters) {
DefaultAssay(SO) <- "SCT"
DEGs <- FindMarkers(SO, ident.1 = "6M_Alp", ident.2 = "WT", group.by = "group" , subset.ident = i, logfc.threshold = .1, min.pct = .1)
DEGs <- DEGs %>% rownames_to_column("gene") %>% filter(p_val_adj < .05)
DEGs <- DEGs[order(DEGs[,"avg_log2FC"], decreasing = TRUE),]
assign(paste0("Alports_4M_",names(clusters[i])), DEGs, envir = DEG.env)

#remove the first column of from the dataframe DEGs
DEGs <- rownames_to_column(DEGs)
DEGs <- DEGs[,-1]

df <- head(DEGs, 20)

df <- df %>%
  kbl(caption = paste("Top 20", i, "Genes Upregulated in 6M_Alp")) %>%
  kable_styling(bootstrap_options = c("striped", "hover"), font_size = 20)

print(df)

top5 <- head(DEGs$gene, 5)

for (j in top5) {
  A <- VlnPlot(SO, j, idents = i, split.by = "group")
  print(A)
}
}

list_objects <- ls(DEG.env)
save(list = list_objects, file = here("outputs", "Alports_4M_Condition_DEGs_6M_Alp_v_WT.Rdata"), envir = DEG.env)

```

# Write DEGs to Excel

```{r echo=TRUE, warning=FALSE, error=FALSE, message=FALSE}

allobj <- ls(DEG.env)
alldf <- sapply(allobj, get, simplify = FALSE, envir = DEG.env)
alldf <- alldf[sapply(alldf, inherits, "data.frame")]

write.xlsx(alldf, sheetName = names(alldf), file = here("outputs", "Alports_4M_Condition_DEGs_6M_Alp_v_WT.xlsx"))

```

# Cluster DEGs for 4M Alports Dataset

```{r echo=TRUE, warning=FALSE, error=FALSE, message=FALSE}

rm(list = ls())

load(here("outputs", "Alports_4M_Condition_DEGs_6M_Alp_v_WT.Rdata"))

# List the objects in the environment
  objects_in_environment <- ls()

data_frames <- Filter(is.data.frame, mget(ls()))

# Initialize an empty data frame to store the results
output_table <- data.frame(Data_Frame = character(),
                           Number_of_Obs = numeric(),
                           Number_of_Positive_Log2FC = numeric(),
                           Number_of_Negative_Log2FC = numeric(),
                           stringsAsFactors = FALSE)

# Loop through each data frame
for (df_name in names(data_frames)) {
  df <- data_frames[[df_name]]
  
  # Get the number of observations in the data frame
  num_obs <- nrow(df)
  
  # Count the number of observations with positive log2FC
  positive_count <- sum(df$avg_log2FC > 0)
  
  # Count the number of observations with negative log2FC
  negative_count <- sum(df$avg_log2FC < 0)
  
  # Create a row in the output table
  output_row <- data.frame(Data_Frame = df_name,
                           Number_of_Obs = num_obs,
                           Number_of_Positive_Log2FC = positive_count,
                           Number_of_Negative_Log2FC = negative_count,
                           stringsAsFactors = FALSE)
  
  # Append the row to the output table
  output_table <- rbind(output_table, output_row)
}

# Print the output table
print(output_table)

```

# Print Graph of DEGs

```{r echo=TRUE, warning=FALSE, error=FALSE, message=FALSE}

# Measure the total number of DEGs (sum of output_table$Number_of_Obs)
v1 <-sum(output_table$Number_of_Obs)
print("Total Number of DEGs")
print(v1)

output_table2 <- output_table %>% 
                 mutate(Data_Frame = sub(".*\\.", "", Data_Frame)) %>%
                 arrange(desc(Number_of_Obs)) %>%
                 mutate(Data_Frame = factor(Data_Frame, levels = unique(Data_Frame)))

p1 <- ggplot(output_table2, aes(x = Data_Frame)) +
  geom_bar(aes(y = Number_of_Positive_Log2FC), stat = "identity", fill = "coral2") +
  geom_bar(aes(y = -Number_of_Negative_Log2FC), stat = "identity", fill = "dodgerblue2") +
  labs(x = "Cell Type", y = "Number of DEGs") +
  ggtitle("Cell Type DEGs 6M_Alp vs. WT") +
  scale_y_continuous(labels = function(x) abs(x)) +
  annotate("text", x = Inf, y = Inf, label = "Positive Log2FC", color = "coral2",
           hjust = 1, vjust = 1, size = 8) +
  annotate("text", x = Inf, y = Inf, label = "Negative Log2FC", color = "dodgerblue2",
           hjust = 1, vjust = 2.1, size = 8) +
  theme_minimal() + 
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        plot.title = element_text(hjust = 0.5, size = 24),
        axis.text = element_text(color = "black", size = 14,),
        axis.text.x = element_text(color = "black", size = 14, angle = 45, hjust = 1, vjust = 1),
        axis.title = element_text(color = "black", size = 20,))

p1

```

## Session Info

```{r, echo=TRUE, warning=FALSE, error=FALSE, message=FALSE}

sessionInfo()

```


  